name: ci-donneve

on:
  pull_request:
    branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.share-status.outputs.status }}

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run coverage

      - name: Check coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "coverage/lcov.info"
          min_coverage: 70
