name: cicd-donneve

on:
  push:
    branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Create .env
        env:
          REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
          REACT_APP_FILESMANAGER_API: ${{ secrets.REACT_APP_FILESMANAGER_API }}
          REACT_APP_DONNEVE_API: ${{ secrets.REACT_APP_DONNEVE_API }}
        run: |
          touch .env
          echo REACT_APP_ENV="$REACT_APP_ENV" >> .env
          echo REACT_APP_FILESMANAGER_API="$REACT_APP_FILESMANAGER_API" >> .env
          echo REACT_APP_DONNEVE_API="$REACT_APP_DONNEVE_API" >> .env
          echo REACT_APP_HOST="https://www.donneve.com/"
          echo REACT_APP_TELEGRAM_BOT="botnorrea_bot"

      - name: Install dependencies
        run: npm i

      - name: Deploy with gh-pages
        run: |
          git config --global user.email "jotacemarin@gmail.com"
          git config --global user.name "Julio Marin"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
